// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace RecommendationSystem
{
    public partial class TracksRecommender
    {
        /// <summary>
        /// model input class for TracksRecommender.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"member_id")]
            public float Member_id { get; set; }

            [ColumnName(@"track_id")]
            public float Track_id { get; set; }

            [ColumnName(@"view_counts_total")]
            public float View_counts_total { get; set; }

            [ColumnName(@"rating")]
            public float Rating { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TracksRecommender.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"member_id")]
            public float Member_id { get; set; }

            [ColumnName(@"track_id")]
            public float Track_id { get; set; }

            [ColumnName(@"view_counts_total")]
            public float View_counts_total { get; set; }

            [ColumnName(@"rating")]
            public float Rating { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TracksRecommender.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
